apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jspark-fastview/botgate
    targetRevision: main
    path: k8s/platform/mimir-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
