apiVersion: v1
kind: Service
metadata:
  name: openresty
  labels:
    app.kubernetes.io/name: openresty
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: openresty
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: metrics
      port: 9145
      targetPort: metrics
