apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: openresty
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openresty
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
