apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace transformer X — extra-rbac.yaml 의 RoleBinding 이 kube-system 에 있어야 함.
# helm chart 의 리소스는 templates 에서 자체 namespace=keda 명시함.

resources:
  - extra-rbac.yaml

helmCharts:
  - name: keda
    repo: https://kedacore.github.io/charts
    version: 2.16.0
    releaseName: keda
    namespace: keda
    valuesFile: values.yaml
    includeCRDs: true
