apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-prod

helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: 8.5.2
    releaseName: grafana-prod
    namespace: monitoring-prod
    valuesFile: values.yaml
    includeCRDs: true
