apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guardus-dev

resources:
- ../../base
- external-secrets.yaml

# 환경 식별 label
labels:
- pairs:
    guardus.io/env: dev

# 이미지 — ECR 경로 + dev tag
images:
- name: guardus/admin-api
  newName: 124052247302.dkr.ecr.ap-northeast-2.amazonaws.com/guardus/admin-api
  newTag: 7a8e4f2c764780e67c591912cb299acf8386a805
- name: guardus/frontend
  newName: 124052247302.dkr.ecr.ap-northeast-2.amazonaws.com/guardus/frontend
  newTag: f2a736e89b79ff17ef36cf49056865a22f53e001
- name: guardus/internal-api
  newName: 124052247302.dkr.ecr.ap-northeast-2.amazonaws.com/guardus/internal-api
  newTag: f2a736e89b79ff17ef36cf49056865a22f53e001
- name: guardus/openresty
  newName: 124052247302.dkr.ecr.ap-northeast-2.amazonaws.com/guardus/openresty
  newTag: f2a736e89b79ff17ef36cf49056865a22f53e001

# 환경별 패치
patches:
- path: patches/openresty-dev.yaml
  target:
    kind: Deployment
    name: openresty
- path: patches/frontend-dev.yaml
  target:
    kind: Deployment
    name: frontend
- path: patches/ingress-dev.yaml
  target:
    kind: Ingress
    name: guardus-ingress
