apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guardus-dev

# bot-ingest-adapter — dev 전용 (검증 후 base 로 promote)
resources:
- ../../base
- external-secrets.yaml
- bot-ingest-adapter.yaml

# 환경 식별 label
labels:
- pairs:
    guardus.io/env: dev

# 이미지 — ECR 경로 + dev tag
images:
- name: guardus/admin-api
  newName: 124052247302.dkr.ecr.ap-northeast-2.amazonaws.com/guardus/admin-api
  newTag: 74f8abd36755a95695ac74fcb72a3710a83f91e1
- name: guardus/bot-ingest-adapter
  newName: 124052247302.dkr.ecr.ap-northeast-2.amazonaws.com/guardus/bot-ingest-adapter
  newTag: 74f8abd36755a95695ac74fcb72a3710a83f91e1
- name: guardus/frontend
  newName: 124052247302.dkr.ecr.ap-northeast-2.amazonaws.com/guardus/frontend
  newTag: 3b61da750ff876b8054bcc038ac37a232fa215e6
- name: guardus/internal-api
  newName: 124052247302.dkr.ecr.ap-northeast-2.amazonaws.com/guardus/internal-api
  newTag: f2a736e89b79ff17ef36cf49056865a22f53e001
- name: guardus/openresty
  newName: 124052247302.dkr.ecr.ap-northeast-2.amazonaws.com/guardus/openresty
  newTag: f2a736e89b79ff17ef36cf49056865a22f53e001

# 환경별 패치
patches:
- path: patches/admin-api-dev.yaml
  target:
    kind: Deployment
    name: admin-api
- path: patches/openresty-dev.yaml
  target:
    kind: Deployment
    name: openresty
- path: patches/frontend-dev.yaml
  target:
    kind: Deployment
    name: frontend
- path: patches/ingress-dev.yaml
  target:
    kind: Ingress
    name: guardus-ingress
