apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guardus-dev

resources:
- ../../base
- external-secrets.yaml
# bot-ingest-adapter — dev 전용 (검증 후 base 로 promote)
- bot-ingest-adapter.yaml

# 환경 식별 label
labels:
- pairs:
    guardus.io/env: dev

# 이미지 — ECR 경로 + dev tag
images:
- name: guardus/admin-api
  newName: 124052247302.dkr.ecr.ap-northeast-2.amazonaws.com/guardus/admin-api
  newTag: 7dcf4a7d62d054360581b7af8270d29f3d9084fa
- name: guardus/frontend
  newName: 124052247302.dkr.ecr.ap-northeast-2.amazonaws.com/guardus/frontend
  newTag: 615dbefefa87bb665c4521efe5356719e9fa7ec4
- name: guardus/internal-api
  newName: 124052247302.dkr.ecr.ap-northeast-2.amazonaws.com/guardus/internal-api
  newTag: f2a736e89b79ff17ef36cf49056865a22f53e001
- name: guardus/openresty
  newName: 124052247302.dkr.ecr.ap-northeast-2.amazonaws.com/guardus/openresty
  newTag: f2a736e89b79ff17ef36cf49056865a22f53e001
- name: guardus/bot-ingest-adapter
  newName: 124052247302.dkr.ecr.ap-northeast-2.amazonaws.com/guardus/bot-ingest-adapter
  newTag: 00c6cf7cfcbfb044905450b6b7d7d2c3fc07bbea

# 환경별 패치
patches:
- path: patches/openresty-dev.yaml
  target:
    kind: Deployment
    name: openresty
- path: patches/frontend-dev.yaml
  target:
    kind: Deployment
    name: frontend
- path: patches/ingress-dev.yaml
  target:
    kind: Ingress
    name: guardus-ingress
